### ISSUE TITLE
Add more tests

### ISSUE THREAD

**Issue by silver659** [CheckiO-Missions/checkio-mission-popular-words#17]
add test to verify words with upper case and lower case like this:
`assert popular_words('''
When i was One
I had just begun
when i was Two
I Was nearly new
''', ['i', 'was', 'three', 'near']) == {
        'i': 4,
        'was': 3,
        'three': 0,
        'near': 0
    }`

**Comment by oduvan** [comment]
You can do it by simply adding a pull-request with this file https://github.com/oduvan/checkio-mission-popular-words/blob/master/verification/tests.py changed.
