### ISSUE TITLE
Incorrect test

### ISSUE THREAD

**Issue by infinitylx** [CheckiO-Missions/checkio-mission-popular-words#20]
`assert list(frequency_sort([4, 6, 2, 2, 6, 4, 4, 4])) == [4, 4, 4, 4, 6, 6, 2, 2]` <-- is incorrect order.

According to:

> If two elements have the same frequency, they should end up in the same order as the first appearance in the list. 

It should be:

` [4, 4, 4, 4, 6, 2, 2, 6]`

**Comment by oduvan** [comment]
You created an issue for the wrong repo

**Comment by infinitylx** [comment]
doesn't matter you didn't fix it any way. 
just close without fixing.

**Comment by freemanlex** [comment]
It's order of first appearance, not exact order of elements! Same elements must be placed together: ...6, 6, 2, 2]
